### ISSUE TITLE
Invalid message protocol error

### ISSUE THREAD

**Issue by newtonsart** [mpi3d/goodix-fp-dump#13]
This is all my output
I have goodix 538d device
```
goodix-fp-dump on  master took 2s 
➜ sudo lsusb -vd "27c6:" | grep "idProduct"
  idProduct          0x538d 

goodix-fp-dump on  master 
➜ sudo python3 run_538d.py                 
#######################################################
This program might break your device.
Consider that it may flash the device firmware.
Continue at your own risk.
But don't hold us responsible if your device is broken!
Don't run this program as part of a regular process.
#######################################################
Type 8718 to continue and confirm that you are not a bot: 8718
__init__(21389, <class 'protocol.USBProtocol'>, 5)
Found Goodix device: "FingerPrint" from "Goodix" on bus 3 address 2.
Found interface data: 0
Found endpoint in: 0x83
Found endpoint out: 0x1
empty_buffer()
nop()
firmware_version()
Traceback (most recent call last):
  File "/home/newton/Coding/kernel/goodix-fp-dump/run_538d.py", line 3, in <module>
    main(0x538d)
  File "/home/newton/Coding/kernel/goodix-fp-dump/driver_53xd.py", line 285, in main
    firmware = device.firmware_version()
  File "/home/newton/Coding/kernel/goodix-fp-dump/goodix.py", line 573, in firmware_version
    check_message_protocol(check_message_pack(self.protocol.read()),
  File "/home/newton/Coding/kernel/goodix-fp-dump/goodix.py", line 132, in check_message_protocol
    raise ValueError("Invalid message protocol")
ValueError: Invalid message protocol
```

**Comment by mpi3d** [comment]
As you might have noticed, the driver is still in developement. So many feature are still missing and doesn't works. You need to stay patient

**Comment by newtonsart** [comment]
aight, thanks :)

**Comment by mpi3d** [comment]
Actually I think you can fix this using the following command.

``` sh
git clone https://github.com/knauth/goodix-521d-explanation.git
cd goodix-521d-explanation/usbreset
gcc usbreset.c -o usbreset.out
sudo ./usbreset.out /dev/bus/usb/{bus}/{device}
```

Then try to run the program again.

If that doesn't works, you will need to try to fix this by yourself. Because I prefer focusing on the libfprint driver right now.

**Comment by newtonsart** [comment]
> Actually I think you can fix this using the following command.
> 
> ```shell
> git clone https://github.com/knauth/goodix-521d-explanation.git
> cd goodix-521d-explanation/usbreset
> gcc usbreset.c -o usbreset.out
> sudo ./usbreset.out /dev/bus/usb/{bus}/{device}
> ```
> 
> Then try to run the program again.
> 
> If that doesn't works, you will need to try to fix this by yourself. Because I prefer focusing on the libfprint driver right now.

This worked. Thanks for your time!

**Comment by mpi3d** [comment]
Ok, good to know.
