### ISSUE TITLE
ValueError: Invalid OTP

### ISSUE THREAD

**Issue by samiurprapon** [mpi3d/goodix-fp-dump#18]
I have seen the [same issue](https://github.com/mpi3d/goodix-fp-dump/issues/16) which is closed but from the comments couldn't figure it out to resolve the issue.

here is the log : - 
```bash
$ sudo python3 run_521d.py 
```

```
__init__(21021, <class 'protocol.USBProtocol'>, 5)
Found Goodix device: "FingerPrint" from "Goodix" on bus 5 address 3.
Found interface data: 0
Found endpoint in: 0x83
Found endpoint out: 0x1
empty_buffer()
nop()
firmware_version()
Firmware: GFUSB_GM168SEC_APP_10019
preset_psk_read(3137470465, 32, 0)
Valid PSK: True
reset(True, False, 20)
read_sensor_register(0, 4)
read_otp()
Traceback (most recent call last):
  File "/home/username/dump/goodix-fp-dump/run_521d.py", line 3, in <module>
    main(0x521d)
  File "/home/username/dump/goodix-fp-dump/driver_52xd.py", line 344, in main
    run_driver(device)
  File "/home/username/dump/goodix-fp-dump/driver_52xd.py", line 133, in run_driver
    raise ValueError("Invalid OTP")
ValueError: Invalid OTP
```

**Comment by mpi3d** [comment]
You need to remove this check in the code.
