### ISSUE TITLE
ValueError: Invalid message pack

### ISSUE THREAD

**Issue by Mike-Wazowsk1** [mpi3d/goodix-fp-dump#23]
Run
```bash
python3.10 run_5110.py
```
Output 
```bash 
__init__(20752, <class 'protocol.USBProtocol'>, 5)
Found Goodix device: "Goodix Fingerprint Device " from "Shenzhen Goodix Technology Co.,Ltd." on bus 3 address 2.
Found interface data: 1
Found endpoint in: 0x81
Found endpoint out: 0x1
empty_buffer()
nop()
enable_chip(True)
nop()
firmware_version()
Firmware: GF_ST411SEC_APP_12117
preset_psk_read(3137470467, None, None)
PSK: 6a410bf328c8c46619af12e160ae2528430257f68fcfbd0d90eaf11cf89f34e2
Valid PSK: True
reset(True, False, 20)
read_sensor_register(0, 4)
read_otp()
reset(True, False, 20)
mcu_switch_to_idle_mode(20)
write_sensor_register(544, b'\xa8\x0b')
write_sensor_register(566, b'\xbb\x00')
write_sensor_register(568, b'\xba\x00')
write_sensor_register(570, b'\xba\x00')
upload_config_mcu(b'p\x11`q,\x9d,\xc9\x1c\xe5\x18\xfd\x00\xfd\x00\xfd\x03\xba\x00\x01\x80\xca\x00\x04\x00\x84\x00\x15\xb3\x86\x00\x00\xc4\x88\x00\x00\xba\x8a\x00\x00\xb2\x8c\x00\x00\xaa\x8e\x00\x00\xc1\x90\x00\xbb\xbb\x92\x00\xb1\xb1\x94\x00\x00\xa8\x96\x00\x00\xb6\x98\x00\x00\x00\x9a\x00\x00\x00\xd2\x00\x00\x00\xd4\x00\x00\x00\xd6\x00\x00\x00\xd8\x00\x00\x00P\x00\x01\x05\xd0\x00\x00\x00p\x00\x00\x00r\x00xVt\x004\x12 \x00\x10@*\x01\x02\x04"\x00\x01 $\x002\x00\x80\x00\x01\x00\\\x00\x80\x00V\x00\x04 X\x00\x03\x022\x00\x0c\x02f\x00\x03\x00|\x00\x00X\x82\x00\x80\x15*\x01\x82\x03"\x00\x01 $\x00\x14\x00\x80\x00\x01\x00\\\x00\x00\x01V\x00\x04 X\x00\x03\x022\x00\x0c\x02f\x00\x03\x00|\x00\x00X\x82\x00\x80\x1f*\x01\x08\x00\\\x00\x80\x00T\x00\x10\x01b\x00\x04\x03d\x00\x19\x00f\x00\x03\x00|\x00\x01X*\x01\x08\x00\\\x00\x00\x01R\x00\x08\x00T\x00\x00\x01f\x00\x03\x00|\x00\x01X\x00\x89.')
set_powerdown_scan_frequency(100)
request_tls_connection()
tls_successfully_established()
query_mcu_state(b'U', True)
mcu_switch_to_fdt_mode(b'\r\x01\xae\xae\xbf\xbf\xa4\xa4\xb8\xb8\xa8\xa8\xb7\xb7', True)
nav()
mcu_switch_to_fdt_mode(b'\r\x01\x80\xaf\x80\xbf\x80\xa3\x80\xb7\x80\xa7\x80\xb6', True)
read_sensor_register(130, 2)
mcu_get_image()
Traceback (most recent call last):
  File "/home/nikolay/goodix-fp-dump/goodix-fp-dump/run_5110.py", line 3, in <module>
    driver_51x0.main(0x5110)
  File "/home/nikolay/goodix-fp-dump/goodix-fp-dump/driver_51x0.py", line 363, in main
    run_driver(device)
  File "/home/nikolay/goodix-fp-dump/goodix-fp-dump/driver_51x0.py", line 292, in run_driver
    device.mcu_get_image(b"\x01\x00",
  File "/home/nikolay/goodix-fp-dump/goodix-fp-dump/goodix.py", line 215, in mcu_get_image
    return check_message_pack(self.protocol.read(), flags)
  File "/home/nikolay/goodix-fp-dump/goodix-fp-dump/goodix.py", line 83, in check_message_pack
    raise ValueError("Invalid message pack")
ValueError: Invalid message pack
```

**Comment by mpi3d** [comment]
Driver is unstable now. Please wait.
